const API='/api';
const state={tasks:[],activities:[],trend:[],analysis:null,taskFilter:'ALL',weekOffset:0,trendDays:30,focusTimer:null,focusSeconds:2700};
let trendChart=null,analyticsChart=null;
const $=id=>document.getElementById(id); const $$=s=>document.querySelectorAll(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const dateKey=v=>{if(!v)return '';const d=new Date(v);return Number.isNaN(d.getTime())?'':new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit'}).format(d)};
const fmtMinutes=m=>{m=Number(m)||0;const h=Math.floor(m/60),r=m%60;return h?`${h}h ${r}m`:`${r}m`};
const fmtTime=v=>{if(!v)return '';const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}).replace(/^0/,'')};
const api=async(path,options={})=>{const c=new AbortController(),t=setTimeout(()=>c.abort(),10000);try{const r=await fetch(`${API}${path}`,{...options,signal:c.signal,headers:{...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})}});clearTimeout(t);if(!r.ok){let msg='Request failed';try{const j=await r.json();msg=j.error||j.message||msg}catch{}throw Error(msg)}return r.json()}catch(e){clearTimeout(t);throw Error(e.name==='AbortError'?'Server request timed out':e.message)}};
function toast(message,type='success'){const box=$('toastContainer'),el=document.createElement('div');el.className=`toast ${type}`;el.textContent=message;box.appendChild(el);requestAnimationFrame(()=>el.classList.add('show'));setTimeout(()=>{el.classList.remove('show');setTimeout(()=>el.remove(),250)},2600)}
function go(view){$$('.view').forEach(v=>v.classList.toggle('hidden',v.id!==view));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===view));if(window.innerWidth<=760)$('sidebar').classList.remove('open');const labels={dashboard:['COMMAND CENTER','Daily Command Center'],tasks:['TASK ENGINE','Task Engine'],activity:['ACTIVITY INTELLIGENCE','Activity Intelligence'],calendar:['CALENDAR','Operating Calendar'],analytics:['ANALYTICS','Productivity Analytics'],insights:['AI INTELLIGENCE','AI Productivity Intelligence'],focus:['FOCUS MODE','Deep Work Session'],goals:['GOALS','Goals & Outcomes'],settings:['SYSTEM','System Settings']};document.title=`PersonalOS — ${labels[view]?.[1]||'Productivity Intelligence'}`;if(view==='analytics')drawAnalytics();if(view==='calendar')renderCalendar();if(view==='goals')renderGoals()}
async function refresh(){try{const [d,t,a,tr,h]=await Promise.all([api(`/analytics/dashboard?date=${localDate()}`),api('/tasks'),api('/activities'),api(`/analytics/trend?days=${state.trendDays}`),api('/health')]);state.tasks=t;state.activities=a;state.trend=tr;updateDashboard(d,h);renderTasks();renderActivities();renderCalendar();renderGoals();drawCharts();setAPIState('online');$('lastSync').textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'});$('dbStatus').textContent=h.mongodb==='connected'?'Connected':'Memory fallback';$('dbStatus').className=h.mongodb==='connected'?'good':''}catch(e){setAPIState('offline');toast(e.message||'Unable to connect to PersonalOS','error')}}
function setAPIState(s){const el=$('sideLatency');el.textContent=s==='online'?'42ms':'OFFLINE'}
function updateDashboard(d,h){$('score').textContent=`${Number(d.productivityScore||0).toFixed(1)}%`;$('scoreMeter').style.width=`${Math.min(100,Number(d.productivityScore||0))}%`;$('done').textContent=`${d.done||0} / ${d.total||0}`;const pct=d.total?Math.round(d.done/d.total*100):0;$('taskPct').textContent=`${pct}%`;$('taskRing').style.transform=`rotate(${pct*3.6}deg)`;$('focus').textContent=fmtMinutes(d.focusMinutes);$('streak').textContent='14 Days';$('todayLabel').textContent=new Date().toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric',weekday:'long'}).toUpperCase();const score=Number(d.productivityScore||0);$('scoreDelta').textContent=score>=70?'▲ 6.2%':'▲ improving';renderMicroBars();renderHourBars();renderNextActions();}
function renderMicroBars(){const f=$('focusBars');f.innerHTML=[28,42,35,55,62,48,74,66,82].map(h=>`<i style="height:${h}%"></i>`).join('');const s=$('streakBars');s.innerHTML=[35,52,40,65,58,76,68,85].map(h=>`<i style="height:${h}%"></i>`).join('')}
function renderHourBars(){const x=$('hourBars');x.innerHTML=[22,35,48,30,58,76,62,82,72,55,45,68,51,74,65,42].map(h=>`<i style="height:${h}%"></i>`).join('')}
function taskProgress(t){if(t.status==='COMPLETED')return 100;if(t.status==='IN_PROGRESS')return Math.min(85,Math.max(20,Math.round((Number(t.actualMinutes||0)/Math.max(1,Number(t.estimatedMinutes||30)))*100)));return 0}
function taskHTML(t,full=false){const done=t.status==='COMPLETED',p=taskProgress(t);return `<div class="${full?'list-task':'task-row'}"><button class="check ${done?'done':''}" data-toggle-task="${esc(t._id)}" title="Toggle task">${done?'✓':''}</button><div><div class="${full?'list-title':'task-name'}">${esc(t.title)}</div><div class="${full?'list-sub':'task-meta'}">${esc(t.category||'General')} · ${Number(t.estimatedMinutes||0)} min</div></div>${full?`<div class="priority ${esc(t.priority)}">${esc(t.priority)}</div><div class="task-progress"><i style="width:${p}%"></i></div><div class="task-time">${fmtMinutes(t.estimatedMinutes)}</div>`:`<div class="priority ${esc(t.priority)}">${esc(t.priority)}</div><div class="task-progress"><i style="width:${p}%"></i></div><button class="dots" data-delete-task="${esc(t._id)}">⋯</button>`}</div>`}
function renderTasks(){const filter=state.taskFilter;const tasks=state.tasks.filter(t=>filter==='ALL'||t.status===filter);$('dashboardTasks').innerHTML=state.tasks.slice(0,5).map(t=>taskHTML(t)).join('')||empty('No tasks yet','Create your first task to activate the execution engine.');$('allTasks').innerHTML=tasks.map(t=>taskHTML(t,true)).join('')||empty('No matching tasks','Change the filter or create a new task.');$('taskCount').textContent=`${tasks.length} tasks`;bindTaskActions()}
function bindTaskActions(){$$('[data-toggle-task]').forEach(b=>b.onclick=()=>toggleTask(b.dataset.toggleTask));$$('[data-delete-task]').forEach(b=>b.onclick=()=>deleteTask(b.dataset.deleteTask))}
async function toggleTask(id){const t=state.tasks.find(x=>String(x._id)===String(id));if(!t)return;try{await api(`/tasks/${id}`,{method:'PUT',body:JSON.stringify({status:t.status==='COMPLETED'?'TODO':'COMPLETED',completedAt:t.status==='COMPLETED'?null:new Date().toISOString()})});toast(t.status==='COMPLETED'?'Task reopened':'Task completed');refresh()}catch(e){toast(e.message,'error')}}
async function deleteTask(id){if(!confirm('Delete this task?'))return;try{await api(`/tasks/${id}`,{method:'DELETE'});toast('Task deleted');refresh()}catch(e){toast(e.message,'error')}}
function activityHTML(a){return `<div class="activity-list"><div class="activity-type">${esc(a.type||'OTHER')}</div><div><div class="activity-title">${esc(a.title)}</div><div class="activity-time">${fmtTime(a.startTime)} · ${esc(a.description||'Captured session')}</div></div><div class="activity-time">${fmtMinutes(a.durationMinutes)}</div><div class="rating">${Number(a.productivityRating||0).toFixed(1)}</div></div>`}
function renderActivities(){const today=state.activities.filter(a=>dateKey(a.startTime)===localDate());const mins=today.reduce((s,a)=>s+Number(a.durationMinutes||0),0),avg=today.length?today.reduce((s,a)=>s+Number(a.productivityRating||0),0)/today.length:0,focus=today.filter(a=>['WORK','STUDY','CODING','TRADING'].includes(a.type)).reduce((s,a)=>s+Number(a.durationMinutes||0),0);$('activityTracked').textContent=fmtMinutes(mins);$('activityQuality').textContent=avg.toFixed(1);$('activityFocus').textContent=fmtMinutes(focus);$('activitySessions').textContent=today.length;$('dashboardActivities').innerHTML=state.activities.slice(0,4).map(a=>`<div class="timeline-row"><i class="timeline-dot"></i><div><div class="timeline-title">${esc(a.title)}</div><div class="timeline-meta">${fmtTime(a.startTime)} · ${fmtMinutes(a.durationMinutes)}</div></div><span class="rating">${Number(a.productivityRating||0).toFixed(1)}</span></div>`).join('')||empty('No activity logged','Start capturing real work sessions.');$('allActivities').innerHTML=state.activities.map(activityHTML).join('')||empty('No activity logged','Your activity timeline will appear here.')}
function empty(title,desc){return `<div class="empty-state"><strong>${esc(title)}</strong><small>${esc(desc)}</small></div>`}
function drawCharts(){if(typeof Chart==='undefined'||!state.trend.length)return;const labels=state.trend.map(x=>new Date(`${x.date}T00:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric'}));const values=state.trend.map(x=>Number(x.productivityScore||0));if(trendChart)trendChart.destroy();trendChart=new Chart($('trendChart'),{type:'line',data:{labels,datasets:[{data:values,borderColor:'#cfff45',backgroundColor:'rgba(207,255,69,.08)',fill:true,tension:.38,pointRadius:0,pointHoverRadius:5,borderWidth:2}]},options:chartOpts('Productivity %')});drawAnalytics()}
function drawAnalytics(){if(typeof Chart==='undefined'||!state.trend.length)return;const labels=state.trend.map(x=>new Date(`${x.date}T00:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric'}));const values=state.trend.map(x=>Number(x.productivityScore||0));if(analyticsChart)analyticsChart.destroy();analyticsChart=new Chart($('analyticsChart'),{type:'bar',data:{labels,datasets:[{data:values,backgroundColor:values.map(v=>v>=75?'#cfff45':'rgba(140,255,193,.35)'),borderRadius:5}]},options:chartOpts('Productivity %')});const t=state.trend.at(-1)||{};$('analyticsCompletion').textContent=`${t.completionRate||0}%`;$('analyticsFocus').textContent=fmtMinutes(t.focusMinutes);$('analyticsQuality').textContent=`${Number(t.avgRating||0).toFixed(1)} / 10`;$('analyticsConsistency').textContent=`${Math.round((Number(t.completionRate||0)*.6+Math.min(Number(t.focusMinutes||0)/240,1)*40))}%`}
function chartOpts(label){return{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{displayColors:false,backgroundColor:'#10171d',borderColor:'rgba(207,255,69,.2)',borderWidth:1,titleColor:'#fff',bodyColor:'#a8b2b5',callbacks:{label:c=>`${label}: ${c.parsed.y}%`}}},scales:{x:{grid:{color:'rgba(255,255,255,.025)'},ticks:{color:'#59666e',font:{size:8},maxTicksLimit:10},border:{display:false}},y:{min:0,max:100,grid:{color:'rgba(255,255,255,.035)'},ticks:{color:'#59666e',font:{size:8},callback:v=>`${v}%`},border:{display:false}}}}}
function renderNextActions(){const list=state.tasks.filter(t=>t.status!=='COMPLETED').sort((a,b)=>({URGENT:0,HIGH:1,MEDIUM:2,LOW:3}[a.priority]??4)-({URGENT:0,HIGH:1,MEDIUM:2,LOW:3}[b.priority]??4)).slice(0,3);$('nextActions').innerHTML=list.map((t,i)=>`<div class="next-item"><span class="next-number">${i+1}</span><div><div class="next-title">${esc(t.title)}</div><div class="next-meta">${esc(t.priority)} impact · ${Number(t.estimatedMinutes||0)} min</div></div><button class="next-go" data-next-task="${esc(t._id)}">→</button></div>`).join('')||empty('Queue clear','No unfinished priority work detected.');$$('[data-next-task]').forEach(b=>b.onclick=()=>go('tasks'))}
async function analyze(){const btn=$('analyzeButton');if(btn){btn.disabled=true;btn.textContent='Analyzing…'}try{const r=await api('/analytics/analyze',{method:'POST',body:JSON.stringify({date:localDate()})});state.analysis=r;$('aiTitle').textContent=r.summary||'Daily intelligence updated.';$('aiSummary').textContent=r.summary||'';$('aiBullets').innerHTML=(r.strengths||[]).slice(0,3).map(x=>`<div class="insight-item"><i></i><span>${esc(x)}</span></div>`).join('');$('insightHeading').textContent=r.summary||'Daily brief updated';$('insightText').textContent=r.summary||'';$('strengths').innerHTML=(r.strengths||[]).map(x=>`<li>${esc(x)}</li>`).join('');$('improvements').innerHTML=(r.improvements||[]).map(x=>`<li>${esc(x)}</li>`).join('');$('tomorrowPlan').innerHTML=(r.tomorrowPlan||[]).map(x=>`<div class="plan-item"><b>${esc(x.task)}</b><small>${esc(x.priority||'MEDIUM')} priority</small></div>`).join('')||empty('No queued actions','Your next plan can be created from unfinished work.');toast('Daily intelligence updated')}catch(e){toast(e.message||'Analysis failed','error')}finally{if(btn){btn.disabled=false;btn.textContent='Get detailed analysis →'}}}
function renderCalendar(){const base=new Date();base.setHours(12,0,0,0);base.setDate(base.getDate()-base.getDay()+1+state.weekOffset*7);$('weekLabel').textContent=`${base.toLocaleDateString(undefined,{month:'short',day:'numeric'})} — ${new Date(base.getTime()+6*86400000).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}`;const days=[];for(let i=0;i<7;i++){const d=new Date(base.getTime()+i*86400000),key=dateKey(d),tasks=state.tasks.filter(t=>dateKey(t.dueDate)===key||dateKey(t.createdAt)===key),acts=state.activities.filter(a=>dateKey(a.startTime)===key);days.push(`<div class="day-column ${key===localDate()?'today':''}"><div class="day-head"><b>${d.toLocaleDateString(undefined,{weekday:'short'}).toUpperCase()}</b><span>${d.getDate()}</span></div>${tasks.slice(0,4).map(t=>`<div class="cal-item">${esc(t.title)}<small>Task · ${esc(t.priority)}</small></div>`).join('')}${acts.slice(0,3).map(a=>`<div class="cal-item" style="border-left-color:var(--accent2)">${esc(a.title)}<small>${fmtTime(a.startTime)} · ${fmtMinutes(a.durationMinutes)}</small></div>`).join('')}${!tasks.length&&!acts.length?'<div style="font-size:7px;color:#3f4c54;margin-top:14px">No activity</div>':''}</div>`)}$('calendarGrid').innerHTML=days.join('')}
function renderGoals(){const goals=[['Build PersonalOS','Ship the intelligence terminal foundation.',72],['Deep Work Consistency','Protect 4 focused sessions each week.',64],['Learning Velocity','Complete 6 structured learning blocks.',48]];$('goalGrid').innerHTML=goals.map(g=>`<article class="goal-card"><span class="section-kicker">ACTIVE OUTCOME</span><h3>${g[0]}</h3><p>${g[1]}</p><div class="goal-progress"><i style="width:${g[2]}%"></i></div><div class="goal-meta"><span>Progress</span><b>${g[2]}%</b></div></article>`).join('')}
function openDialog(id){$(id).showModal()};function closeDialogs(){$$('dialog[open]').forEach(d=>d.close())}
async function saveTask(e){e.preventDefault();const p={title:$('taskTitle').value.trim(),description:$('taskDesc').value.trim(),priority:$('taskPriority').value,category:$('taskCategory').value.trim()||'General',estimatedMinutes:Math.max(1,Number($('taskMinutes').value)||30),dueDate:$('taskDue').value?new Date(`${$('taskDue').value}T12:00:00`).toISOString():null};if(!p.title)return;try{await api('/tasks',{method:'POST',body:JSON.stringify(p)});closeDialogs();e.target.reset();toast('Task created');refresh()}catch(err){toast(err.message,'error')}}
async function saveActivity(e){e.preventDefault();const p={title:$('actTitle').value.trim(),type:$('actType').value,durationMinutes:Math.max(0,Number($('actDuration').value)||0),productivityRating:Number($('actRating').value)||5,description:$('actDesc').value.trim(),startTime:new Date().toISOString()};if(!p.title)return;try{await api('/activities',{method:'POST',body:JSON.stringify(p)});closeDialogs();e.target.reset();$('ratingValue').textContent='8 / 10';toast('Activity recorded');refresh()}catch(err){toast(err.message,'error')}}
function initClock(){const tick=()=>{const d=new Date();$('headerDate').textContent=d.toLocaleDateString(undefined,{weekday:'short',day:'2-digit',month:'short',year:'numeric'}).toUpperCase();$('headerTime').textContent=d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',hour12:true})};tick();setInterval(tick,1000)}
function initSettings(){const defs=[['compactMode','compact'],['motionMode','motion'],['timeMode','24h']];defs.forEach(([id,key])=>{const el=$(id),v=localStorage.getItem(`pos_${key}`)==='1';el.checked=v;el.onchange=()=>localStorage.setItem(`pos_${key}`,el.checked?'1':'0')});$('storageMode').textContent='Local browser + API'}
function initFocus(){const update=()=>{const s=Math.max(0,state.focusSeconds),m=Math.floor(s/60),r=s%60;$('focusTimer').textContent=`${String(m).padStart(2,'0')}:${String(r).padStart(2,'0')}`};$('focusMinutes').onchange=e=>{state.focusSeconds=Number(e.target.value)*60;update()};$('focusStart').onclick=()=>{if(state.focusTimer)return;state.focusTimer=setInterval(()=>{state.focusSeconds--;update();if(state.focusSeconds<=0){clearInterval(state.focusTimer);state.focusTimer=null;toast('Focus block complete')}} ,1000);$('focusStart').textContent='Running…'};$('focusReset').onclick=()=>{clearInterval(state.focusTimer);state.focusTimer=null;state.focusSeconds=Number($('focusMinutes').value)*60;update();$('focusStart').textContent='Start focus'};update()}
function bind(){ $$('.nav').forEach(n=>n.onclick=()=>go(n.dataset.view));$$('[data-view-target]').forEach(b=>b.onclick=()=>go(b.dataset.viewTarget));$('mobileMenu').onclick=()=>$('sidebar').classList.toggle('open');$('newTaskBtn').onclick=()=>openDialog('taskDialog');$('tasksAddBtn').onclick=()=>openDialog('taskDialog');$('calendarTaskBtn').onclick=()=>openDialog('taskDialog');$('logActivityBtn').onclick=()=>openDialog('activityDialog');$('activityAddBtn').onclick=()=>openDialog('activityDialog');$('quickAnalyze').onclick=()=>{go('insights');analyze()};$('analyzeButton').onclick=()=>analyze();$('insightsAnalyze').onclick=()=>analyze();$('analyticsRefresh').onclick=()=>refresh();$('prevWeek').onclick=()=>{state.weekOffset--;renderCalendar()};$('nextWeek').onclick=()=>{state.weekOffset++;renderCalendar()};$('todayWeek').onclick=()=>{state.weekOffset=0;renderCalendar()};$('taskForm').onsubmit=saveTask;$('activityForm').onsubmit=saveActivity;$('actRating').oninput=e=>$('ratingValue').textContent=`${e.target.value} / 10`;$$('[data-close]').forEach(b=>b.onclick=closeDialogs);$$('[data-task-filter]').forEach(b=>b.onclick=()=>{$$('[data-task-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.taskFilter=b.dataset.taskFilter;renderTasks()});$$('.chart-tab').forEach(b=>b.onclick=()=>{state.trendDays=Number(b.dataset.range);$$('.chart-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');refresh()});$('globalSearch').oninput=e=>{const q=e.target.value.toLowerCase().trim();if(!q)return;const match=state.tasks.find(t=>t.title.toLowerCase().includes(q));if(match)go('tasks')};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('globalSearch').focus()}if(e.key.toLowerCase()==='n'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();openDialog('taskDialog')}if(e.key==='Escape')closeDialogs()})}
document.addEventListener('DOMContentLoaded',()=>{bind();initClock();initSettings();initFocus();go('dashboard');refresh();setInterval(()=>document.visibilityState==='visible'&&refresh(),60000)});
